[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prixfixe"
version = "0.0.0"
requires-python = ">=3.9"
description = "A minimal example package"
license = {text = "de Boer lab"}
dependencies = [
    "torch",
]
